spring.application.name=smartcampus

# Server
server.port=8080

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5434/${POSTGRES_DB}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Data initialization
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# Flyway
spring.flyway.enabled=false

# Multipart (file uploads)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# File upload directory
app.upload-dir=uploads

# Logging
logging.level.com.campushub.smartcampus=DEBUG
logging.level.org.hibernate.SQL=DEBUG